FROM ubuntu:bionic

WORKDIR /acalc

RUN : \
    && apt-get update \
    && apt-get install -y \
        libfl-dev \
        python3-pip \
        valgrind \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN pip3 install --no-cache-dir -U pip

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .
