FROM alpine

WORKDIR /acalc

RUN apk add --no-cache \
    bash \
    build-base \
    flex-dev \
    libxml2-dev \
    libxslt-dev \
    python3-dev

RUN : \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && ln -s /usr/bin/pip3 /usr/bin/pip \
    && :

RUN pip install --no-cache-dir -U pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
